# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fcb7f17a46fec2e15fc9943978b7f66bf80d375dafc1fcba15fb3dffbb66b447bb2a51f37885944f3b1305fd4d5c0c22f1fb2b2a3a21c4b4640b8da5e434f56f

test:
  secret_key_base: 87fc559347ef36193e0d0ce8a3b8494f1dfa029ef19d3b5ec2f1127713e13c44bc3080f7edaece9cfac73e629161eb80bb30b483cb74526406e68d453232371a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
